name: store_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # build system for Dart code generation and modular compilation.
  build_runner: ^2.4.12
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.5.6
  freezed_annotation: ^2.4.4
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  # NotWorking
  dio: ^5.7.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.4
  pretty_dio_logger: ^1.4.0
  # for splach screen
  flutter_native_splash: ^2.4.4
  # Dependency injection
  get_it: ^8.0.3
  # for adapting screen and font size
  flutter_screenutil: ^5.9.3
  # State management
  flutter_bloc: ^9.0.0
  # Customizable animated page 
  smooth_page_indicator: ^1.2.0+3
  # A simple slide-to-action widget for Flutter
  slide_to_act: ^2.0.2
  # An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.0.16
  # A carousel slider widget, support infinite scroll and custom child widget.
  carousel_slider_plus: ^7.1.0
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0
  # Converts already built widgets into skeleton loaders with no extra effort.
  skeletonizer: ^1.4.3
  # Data Save
  hive: ^2.2.3
  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^2.0.1
  # getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
